import { Inter } from 'next/font/google';
import './globals.css';
import AosInit from '@/components/AosInit.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'CHIKEZIE TEDDY OHIAGU-ANANABA',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <AosInit/>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
